typography_spectrum: 0.33593832212500274
color:
  brandStrength: 0.10179639863781631
  lightness: 0.3910482774954289
  saturation: 0.42488195677287877
  rhythmicContrast: 0.711676656967029
  brandColors:
    - '#F3F9F7'
    - '#C7C7C7'
    - '#1D271E'
    - '#A15E33'
    - '#587D85'
layout_spectrum: 0.5404031069483608
analytics:
  google: UA-110547943-1
author:
  name: A.I
  email: a.i@acm.org
name: Imjin War
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Imjin War 1592-98
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fw6bHeEDB6DE%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dw6bHeEDB6DE&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fw6bHeEDB6DE%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=w6bHeEDB6DE'
      keywords:
        - dancheong
        - 단청
      related: []
      author:
        - name: je Kwon
          url: 'https://www.youtube.com/user/kamalanote'
          avatar: {}
      '@context': 'http://schema.org'
      title: Korean tradition crafts experience - Dancheong
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=w6bHeEDB6DE&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=w6bHeEDB6DE&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=w6bHeEDB6DE&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=w6bHeEDB6DE&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=w6bHeEDB6DE&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=w6bHeEDB6DE'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=w6bHeEDB6DE
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=w6bHeEDB6DE
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      description: Korean tradition crafts experience Dancheong (Ornamental Painting)
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a987be40-b795-4353-80ce-210d43e44664.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a987be40-b795-4353-80ce-210d43e44664.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/63ddad58-4098-4460-ad02-25e08cc58e71.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/63ddad58-4098-4460-ad02-25e08cc58e71.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  This project named Imjin War is a board game of the conflict on Korean
  peninsula  between Joseon, Japan and Ming dynasty.
purpose:
  - type: contact
    url: 'mailto:a.i@acm.org'
    label: Contact me
github: true
content_rating:
  adult: false
