typography_spectrum: 0.33593832212500274
color:
  brandStrength: 0.10179639863781631
  lightness: 0.3910482774954289
  saturation: 0.42488195677287877
  rhythmicContrast: 0.711676656967029
  brandColors:
    - '#F3F9F7'
    - '#C7C7C7'
    - '#1D271E'
    - '#A15E33'
    - '#587D85'
layout_spectrum: 0.5404031069483608
analytics:
  google: UA-110547943-1
author:
  name: A.I
  email: a.i@acm.org
name: Imjin War
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Imjin War 1592-98
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FkvkpTX0yjjs%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkvkpTX0yjjs&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FkvkpTX0yjjs%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Taeseok Kim
          url: 'https://www.youtube.com/channel/UCUueJeZbgC6hrqvh4NwVLlw'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - animation
        - digital folding screen
        - jinju national museum
        - jeongyujaeran
        - the 2nd japanese invasion
        - defeat of the japanese invaders 애니메이션
        - 디지털 병풍
        - 국립진주박물관
        - 정...
      description: >-
        작품명 : 정왜기공도병 제작년도 : 2017 제작기법 : 2D 디지털 애니메이션 작품크기 : 빔 프로젝터 (1080p Full
        HD) 작품길이 : 4분 43초, 반복재생 전시명 : 정유재란 1597 전시기간 : 2017.07.25. ~ 2017.10.22.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=kvkpTX0yjjs&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=kvkpTX0yjjs&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=kvkpTX0yjjs&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=kvkpTX0yjjs&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=kvkpTX0yjjs&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=kvkpTX0yjjs'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=kvkpTX0yjjs
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=kvkpTX0yjjs
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/kvkpTX0yjjs'
      title: 정왜기공도병 (국립진주박물관 전시)
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  This site is for board game project "Imjin War", the conflict on Korean
  peninsula  between Joseon, Japan and Ming dynasty.
purpose:
  - type: contact
    url: 'mailto:a.i@acm.org'
    label: Contact me
github: true
content_rating:
  adult: false
